series: GLFW Graphics
title: Point Lighting
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This program demonstrates an implementation for point lighting in a scene.
language: C++
tags:
  - Graphics
extra_resources:
  - title: Even more lighting, an article by Tom Dalling
    link: "http://www.tomdalling.com/blog/modern-opengl/08-even-more-lighting-directional-lights-spotlights-multiple-lights/"
connections:
  - series: GLM Math
    title: Rotation Matrix Tutorial
